server:
  port: 8093
  servlet:
    context-path: /word

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.18:3006/english_words?useUnicode=true&characterEncoding=UTF8&autoReconnect=true
    username: root
    password: root

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/